# Generated by Django 3.2 on 2024-10-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название меню')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Named URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Предок')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'меню',
            },
        ),
    ]
